### ISSUE TITLE
Shift view shows (lots of) shifts I am not allowed to do

### ISSUE THREAD

**Issue by RalfJung** [engelsystem/engelsystem#229] opened 2015-12-27 20:00 UTC
Per default, int eh Shift view, all the angel types are enabled even if I am just member of a few of them. There is some footnote indicating that the view could depend on the angel types I am a member of, but that doesn't seem to completely work.

For example, if I enable only the angel types I am in plus Heralds, I get lots of events shown where I cannot take any shift: Events with missing heralds, but also events with missing Food Angels or CERT Coordinators.

The result is that I have to manually sync the checklist in the shift view, with my group membership.

This is potentially covered by #164, but I thought it was confusing enough for new angels (it certainly confused me) to warrant its own issue. One nice fix would be to automatically hide all checkboxes in the shift view, that are for types I am not a member of, and treat them all as disabled.

**Comment by 20-100** [comment] 2015-12-30 01:01
It is actually very useful to be allowed to see the shifts even if you're not able to subscribe them. In that way, you will be able to know who is the coordinator for that shift before subscribing it. Maybe there's none, maybe you don't like him/her, maybe you *do* like him/her and want to work with him/her again.

Also I cannot reproduce your "I see events where I cannot take any shifts"-bug. I'm only shown shifts where the angeltypes I've ticked *can* still take shifts. Maybe you ticked the "occupied" box? (in which case you are shown all shifts where ticked AngelTypes are concerned, no matter that there is still some needed or not)

**Comment by RalfJung** [comment] 2015-12-30 12:45
Here's a screenshot of how the shift view looks for me right now per default - that is, with all ticks set except for "occupied".

![screenshot from 2015-12-30 13-43-57](https://cloud.githubusercontent.com/assets/330628/12050885/80f1f326-aefb-11e5-9683-44dae78cb479.png)

As you can see, the four columns on the right (all related to CERT) have no open position I can actually fill.

**Comment by RalfJung** [comment] 2015-12-30 12:50
Maybe I should mention that there's dozens of further events with the same problem, including some talks. This is not at all specific to CERT. The issue also comes up with the "old" view:

![screenshot from 2015-12-30 13-48-32](https://cloud.githubusercontent.com/assets/330628/12050908/156ff9bc-aefc-11e5-9aac-ae94cfcda284.png)

Both of these talks only have free positions for Microphone Angel and Video Trainee, neither of which I can fill.

**Comment by msquare** [comment] 2018-10-31 12:55
Maybe we should reintroduce the "Become <angeltype>" button in shift views, as it is shown at the last screenshot.

**Comment by msquare** [comment] 2019-11-03 10:00
I close this issue now. We show as much shifts to the user as possible by design. This is to motivate users to join other angeltypes.

- We added a button to select only your own angeltypes on shift calendar view. 
- We added a button "become angeltype" to encourage joining a new angeltype.
- We added a special color to shifts a user cannot join because of mismatching angeltypes.

**Closed by msquare** 2019-11-03 10:00 UTC
Labels: Type: Bug(fix)
