### ISSUE TITLE
"For dect numbers are only 5 digits allowed.

### ISSUE THREAD

**Issue by Lokke** [engelsystem/engelsystem#529] opened 2018-12-18 12:25 UTC

**Comment by MyIgel** [comment] 2018-12-18 12:40
Ah, it could be useful for EPVPN so it's a duplicate of #529 (EPVPN number in DECT field is shortened)

**Comment by zivillian** [comment] 2018-12-20 19:01
@eventphone is also using temporary numbers for DECT & GSM, which are currently eight digits.

**Closed** 2018-12-22 11:03 UTC
Labels: Bug(fix), Feature
