### ISSUE TITLE
Rights: Two Character Cutoff

### ISSUE THREAD

**Issue by NilsKet** [engelsystem/engelsystem#356] opened 2017-11-19 13:12 UTC
(Minor issue)

When displaying a user, the first two characters of each right are cut off. Either it should be enforced that the first two characters of each right are the number for sorting (as in "2-Engel") or the cutoff should be removed when displaying. 

Currently some users are shown with rights like "irt-Manager" and "ws-Admin" which is not the intended way to display.

Example: https://staging.engelsystem.de/test/users?action=view&user_id=2077

**Comment by NilsKet** [comment] 2017-11-19 15:11
I think this is also the problem described in #318

**Comment by msquare** [comment] 2017-11-29 10:27
Yes. Duplicate of #318

**Closed by msquare** 2017-11-29 10:27 UTC
