### ISSUE TITLE
rename sign-up to register/registration

### ISSUE THREAD

**Issue by xuwhite** [engelsystem/engelsystem#1250] opened 2023-11-12 14:58 UTC
In addition to #1220 in the whole codebase the registration sign-up should be renamed to registration.

**Comment by MyIgel** [comment] 2023-11-12 16:47
Duplicate of #1220

**Comment by xuwhite** [comment] 2023-11-12 16:51
> Duplicate of #1220

it is not 
this is code based the other one is UI

**Comment by xuwhite** [comment] 2023-11-12 16:54
in extension of #1220

**Closed** 2023-11-12 17:35 UTC
