### ISSUE TITLE
error 500 after installation

### ISSUE THREAD

**Issue by MZLXXXXX** [engelsystem/engelsystem#1150] opened 2023-06-17 13:33 UTC
Hi all,

I installed the rC3-nowhere Stable version with following specs/processes:
- Debian 11
- PHP 8.1
- MySQL version: 10.5.19-MariaDB-0+deb11u2 through PHP extension MySQLi
- Iinstalled everything from the composer.json 
- first, I added install-v3.3.0.sql, second I added initial-install.sql to the database

Now I have an error 500 and my error log says:

`[Sat Jun 17 13:23:11.501407 2023] [php:error] [pid 1313] [client 95.163.175.64:22535] PHP Fatal error:  Declaration of Engelsystem\\Http\\Request::getServerParams() must be compatible with Psr\\Http\\Message\\ServerRequestInterface::getServerParams(): array in /var/www/src/Http/Request.php on line 222`

Any hints are appreciated.
Thanks in advance

**Comment by MyIgel** [comment] 2023-07-10 11:36
Hi, importing one of the two files is enough ;)
The issue is already fixed in the main branch (which normally can be used without any problems) so to fix the issue you could just use that one (but then have to run the cli commands instead of importing the .sql or get the .sql file for the coresponding commit from https://chaos.expert/engelsystem/engelsystem/-/artifacts (dump-database stage))

**Comment by MyIgel** [comment] 2023-11-12 14:56
The newest release should fix even more bugs with current webhosting envs, if you still have problems feel free to re-open this issue :)

**Closed by MyIgel** 2023-11-12 14:56 UTC
Labels: Type: Question
