### ISSUE TITLE
Sign up button and needed helpers only half visible on short/one hour shifts

### ISSUE THREAD

**Issue by simonkoenig** [engelsystem/engelsystem#668] opened 2019-10-26 17:09 UTC
![Unbenannt](https://user-images.githubusercontent.com/4437584/67623279-8cb92b00-f823-11e9-91e6-60e7ed2284db.JPG)

**Comment by MyIgel** [comment] 2019-10-26 17:17
Did you rebuild the CSS and JS files?
After the merge of #665 (Expand shift panel) they have to be rebuild ;)

**Comment by simonkoenig** [comment] 2019-10-27 10:38
No I didn't. I have used the 35C3 stable release, but I'll build it from
source then. Thanks


Igor Scheller <notifications@github.com> schrieb am Sa., 26. Okt. 2019,
19:17:

**Comment by MyIgel** [comment] 2019-10-27 12:14
As this is then a duplicate of #526 (Not all angels shown in shift overview) i'll close the issue for now. If you have any further questions on using the `master` branch feel free to ask :)

**Closed by MyIgel** 2019-10-27 12:14 UTC
